iapiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-app
  namespace: ivolve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-app
  template:
    metadata:
      labels:
        app: jenkins-app
    spec:
      containers:
        - name: jenkins-app
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 3000

