apiVersion: v1
kind: Service
metadata:
  name: jenkins-app-service
  namespace: ivolve
spec:
  type: ClusterIP
  selector:
    app: jenkins-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

